ci: Make sqlc CI job more general and test for mockgen changes
This adds a check for uncommited `make mock` changes on CI. Thus ensuring that
folks don't merge code without updating the mocks as needed.

Note that this was added to the same job that runs the sqlc checks because
it would run `make bootstrap` twice otherwise, which is time-taking and wasteful.

diff --git a/.github/workflows/generation.yml b/.github/workflows/generation.yml
--- a/.github/workflows/generation.yml
+++ b/.github/workflows/generation.yml
@@ -47,7 +47,7 @@ jobs:
         with:
           against: "https://github.com/stacklok/mediator.git#branch=main"
 
-  sqlc-generation:
+  code-generation:
     runs-on: ubuntu-latest
 
     steps:
@@ -70,4 +70,13 @@ jobs:
 
       - name: Check for uncommitted SQLC changes
         run: |
-          git diff --exit-code || (echo "Error: Uncommitted changes detected after running 'sqlc generate'. Please commit the changes and try again." && exit 1)
+          git diff --exit-code || (echo "Error: Uncommitted changes detected after running 'make sqlc'. Please commit the changes and try again." && exit 1)
+
+      - name: Generate Go code for mocks
+        shell: bash
+        run: |
+          make mock
+
+      - name: Check for uncommitted Mock changes
+        run: |
+          git diff --exit-code || (echo "Error: Uncommitted changes detected after running 'make mock'. Please commit the changes and try again." && exit 1)
