More suitable test name
Signed-off-by: Luke Hinds <luke@stacklok.com>

diff --git a/.github/workflows/generation.yml b/.github/workflows/generation.yml
--- a/.github/workflows/generation.yml
+++ b/.github/workflows/generation.yml
@@ -9,7 +9,7 @@ on:
       - main
 
 jobs:
-  generate:
+  test:
     runs-on: ubuntu-latest
 
     steps:
@@ -33,10 +33,14 @@ jobs:
       run: |
         OUTPUT=$(sqlc generate 2>&1) || true
         if [[ $OUTPUT == *"syntax error"* ]]; then
-          echo "Error: SQL syntax error detected:"
+          echo "Error: SQL generation failed:"
           echo "$OUTPUT"
           exit 1
         else
           echo "$OUTPUT"
         fi
+    
+    - name: Check for uncommitted SQLC changes
+      run: |
+        git diff --exit-code || (echo "Error: Uncommitted changes detected after running 'sqlc generate'. Please commit the changes and try again." && exit 1)
 
